-- Services: mobile pricing and per-service buffer time
ALTER TABLE services ADD COLUMN IF NOT EXISTS mobile_price DECIMAL(10,2) DEFAULT NULL;
ALTER TABLE services ADD COLUMN IF NOT EXISTS buffer_minutes INTEGER NOT NULL DEFAULT 0;
ALTER TABLE services ADD COLUMN IF NOT EXISTS category VARCHAR(100) DEFAULT NULL;
ALTER TABLE services ADD COLUMN IF NOT EXISTS deposit_required BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE services ADD COLUMN IF NOT EXISTS deposit_amount DECIMAL(10,2) DEFAULT NULL;

-- Businesses: travel settings
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS travel_radius_km INTEGER DEFAULT NULL;
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS travel_charge DECIMAL(10,2) DEFAULT NULL;
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS booking_lead_minutes INTEGER NOT NULL DEFAULT 0;
