import { useEffect, useState } from 'react';
import { MessageSquare, Send, Calendar } from 'lucide-react';
import toast from 'react-hot-toast';
import { inboxAPI } from '../../services/api';
import { EmptyState, ErrorState, SkeletonList } from '../../components/shared/AsyncState';

const initials = n => (n || '?').split(' ').map(x => x[0]).join('').slice(0, 2).toUpperCase();
const stamp = t => t ? new Date(t).toLocaleString('en-GB', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' }) : '';

export default function AdminInbox() {
  const [rooms, setRooms] = useState([]), [active, setActive] = useState(null), [detail, setDetail] = useState(null);
  const [text, setText] = useState(''), [channel, setChannel] = useState('in_app');
  const [loading, setLoading] = useState(true), [failed, setFailed] = useState(false);
  const refresh = () => { setFailed(false); return inboxAPI.conversations().then(setRooms).catch(e => { setFailed(true); toast.error(e.message || 'Could not load inbox'); }).finally(() => setLoading(false)); };
  useEffect(() => { refresh(); const timer = setInterval(refresh, 15000); return () => clearInterval(timer); }, []);
  const open = async id => { setActive(id); try { setDetail(await inboxAPI.detail(id)); } catch (e) { toast.error(e.message || 'Could not load conversation'); } };
  const send = async e => { e.preventDefault(); if (!text.trim()) return; try { const m = await inboxAPI.send(active, { content: text, channel }); setDetail(d => ({ ...d, messages: [...d.messages, m] })); setText(''); refresh(); if (m.status === 'queued') toast('Queued — this provider is not configured.'); } catch (e) { toast.error(e.message || 'Could not send message'); } };
  return <div className="animate-fade-in flex rounded-2xl overflow-hidden border" style={{ height: 'min(calc(100dvh - 8rem), 720px)', borderColor: 'var(--bam-border)', background: 'var(--bam-surface)' }}>
    <aside className={`${active ? 'hidden md:flex' : 'flex'} w-full md:w-80 flex-col border-r`} style={{ borderColor: 'var(--bam-border)' }}><div className="p-4 border-b flex gap-2" style={{ borderColor: 'var(--bam-border)' }}><MessageSquare className="text-primary-600"/><div><h1 className="font-bold" style={{ color: 'var(--bam-text)' }}>Messages</h1><p className="text-xs" style={{ color: 'var(--bam-text-muted)' }}>Unified customer inbox</p></div></div><div className="overflow-y-auto p-2">{loading ? <SkeletonList rows={5} /> : failed ? <ErrorState onRetry={refresh} /> : rooms.map(r => <button key={r.id} onClick={() => open(r.id)} className={`w-full flex gap-3 p-4 text-left border-b ${active === r.id ? 'bg-primary-50 dark:bg-primary-950/20' : ''}`} style={{ borderColor: 'var(--bam-border)' }}><div className="w-10 h-10 rounded-full bg-primary-100 text-primary-700 flex items-center justify-center font-bold">{initials(r.customer_name)}</div><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><b className="truncate text-sm" style={{ color: 'var(--bam-text)' }}>{r.customer_name}</b><span className="text-[10px]" style={{ color: 'var(--bam-text-muted)' }}>{stamp(r.last_message_at)}</span></div><p className="truncate text-xs mt-1" style={{ color: 'var(--bam-text-muted)' }}>{r.last_message_preview || 'No messages yet'}</p>{r.upcoming_booking && <p className="text-[10px] text-primary-600 mt-1 truncate">{r.upcoming_booking.service_name} · {r.upcoming_booking.booking_date}</p>}</div>{r.unread_count > 0 && <span className="text-xs bg-primary-600 text-white rounded-full h-5 w-5 text-center">{r.unread_count}</span>}</button>)}{!loading && !failed && !rooms.length && <EmptyState icon="💬" title="No conversations yet." description="Customer conversations will appear here when you start a message or receive one." />}</div></aside>
    <main className={`${active ? 'flex' : 'hidden md:flex'} flex-1 flex-col min-w-0`}>{detail ? <><header className="p-4 border-b flex justify-between" style={{ borderColor: 'var(--bam-border)' }}><div className="flex gap-2"><div className="w-9 h-9 rounded-full bg-primary-100 text-primary-700 flex items-center justify-center font-bold">{initials(detail.conversation.full_name)}</div><div><b style={{ color: 'var(--bam-text)' }}>{detail.conversation.full_name}</b><p className="text-xs" style={{ color: 'var(--bam-text-muted)' }}>{detail.conversation.email || detail.conversation.phone}</p></div></div>{detail.upcoming_booking && <div className="text-xs text-right"><Calendar className="w-3 inline mr-1"/>{detail.upcoming_booking.service_name}<p>{detail.upcoming_booking.booking_date} {String(detail.upcoming_booking.start_time).slice(0,5)}</p></div>}</header><div className="flex-1 overflow-y-auto p-4 space-y-3">{detail.messages.map(m => <div key={m.id} className={`max-w-[80%] rounded-2xl p-3 text-sm ${m.direction === 'outbound' ? 'bg-primary-600 text-white ml-auto' : 'bg-gray-100 dark:bg-gray-800'}`} style={m.direction === 'outbound' ? {} : { color: 'var(--bam-text)' }}><p>{m.content}</p><small className="opacity-70">{m.channel} · {m.status} · {stamp(m.created_at)}</small></div>)}</div><div className="px-4 text-xs" style={{ color: 'var(--bam-text-muted)' }}>{detail.previous_bookings.length} bookings in customer history</div><form onSubmit={send} className="p-3 border-t flex gap-2" style={{ borderColor: 'var(--bam-border)' }}><select className="input w-28" value={channel} onChange={e => setChannel(e.target.value)}><option value="in_app">In-app</option><option value="email">Email</option><option value="sms">SMS</option><option value="whatsapp">WhatsApp</option></select><input className="input flex-1" value={text} onChange={e => setText(e.target.value)} placeholder="Write a message…"/><button className="btn-primary px-3"><Send className="w-4"/></button></form></> : <div className="m-auto text-center"><MessageSquare className="w-10 h-10 mx-auto opacity-30"/><p className="mt-2" style={{ color: 'var(--bam-text-muted)' }}>Select a conversation</p></div>}</main>
  </div>;
}
