import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { intelligenceAPI } from '../../services/api';

export default function Intelligence() {
  const [data, setData] = useState(null);
  useEffect(() => { intelligenceAPI.overview().then(setData).catch(() => setData({ error: true })); }, []);
  if (!data) return <div className="h-64 animate-pulse rounded-2xl" style={{ background: 'var(--bam-surface)' }} />;
  if (data.error) return <p>Unable to load intelligence.</p>;
  const i = data.insights;
  return <div className="space-y-6 animate-fade-in"><div><h1 className="text-2xl font-bold" style={{ color: 'var(--bam-text)' }}>BookAm Intelligence</h1><p className="text-sm mt-1" style={{ color: 'var(--bam-text-muted)' }}>Recommendations grounded in your BookAm business data</p></div>{!data.sufficient_data && <div className="p-4 rounded-2xl bg-amber-50 text-amber-800">I don't have enough data to answer detailed questions yet.</div>}<div className="grid sm:grid-cols-3 gap-3"><Card label="Revenue (7 days)" value={`€${i.revenue_7d.toFixed(2)}`}/><Card label="Bookings this week" value={i.booking_trend.current}/><Card label="Booking trend" value={i.booking_trend.change_percent == null ? '—' : `${i.booking_trend.change_percent}%`}/></div><section><h2 className="font-bold mb-3" style={{ color: 'var(--bam-text)' }}>Recommendations</h2><div className="space-y-2">{data.recommendations.map((r,n) => <div key={n} className="p-4 rounded-2xl flex justify-between gap-3" style={{ background: 'var(--bam-surface)', border: '1px solid var(--bam-border)' }}><p>{r.text}</p><Link className="text-sm font-bold text-primary-600 whitespace-nowrap" to={r.action === 'open_availability' ? '/admin/settings' : r.action === 'adjust_service' ? '/admin/services' : r.action === 'message_customers' ? '/admin/messages' : '/admin/bookings'}>Act</Link></div>)}{!data.recommendations.length && <p style={{ color: 'var(--bam-text-muted)' }}>No data-backed recommendations yet.</p>}</div></section><section className="grid lg:grid-cols-2 gap-5"><List title="Popular services" rows={i.popular_services.map(x => `${x.name} — €${x.revenue.toFixed(2)} · ${x.bookings} bookings`)}/><List title="Highest-value customers" rows={i.highest_value_customers.map(x => `${x.full_name} — €${x.lifetime_value.toFixed(2)}`)}/><List title="Staff performance" rows={i.staff_performance.map(x => `${x.name} — ${x.bookings} bookings (last 30 days)`)}/><List title="Retention & attendance" rows={[`${i.customers_due} customers due for an appointment`, `${i.cancellation_trends.cancelled} cancellations in 30 days`, `${i.cancellation_trends.no_shows} no-shows in 30 days`]}/></section></div>;
}
function Card({ label, value }) { return <div className="p-5 rounded-2xl" style={{ background: 'var(--bam-surface)', border: '1px solid var(--bam-border)' }}><p className="text-xs" style={{ color: 'var(--bam-text-muted)' }}>{label}</p><p className="text-2xl font-bold mt-1" style={{ color: 'var(--bam-text)' }}>{value}</p></div>; }
function List({ title, rows }) { return <div className="p-5 rounded-2xl" style={{ background: 'var(--bam-surface)', border: '1px solid var(--bam-border)' }}><h2 className="font-bold mb-3" style={{ color: 'var(--bam-text)' }}>{title}</h2>{rows.length ? rows.map((r,i) => <p key={i} className="py-2 text-sm border-b last:border-0" style={{ color: 'var(--bam-text-muted)', borderColor: 'var(--bam-border)' }}>{r}</p>) : <p className="text-sm" style={{ color: 'var(--bam-text-muted)' }}>I don't have enough data to answer that yet.</p>}</div>; }
